name: Deploy to Develop s3

on:
    push:
        branches:
            - develop

jobs:
    build:
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: setup node
              uses: actions/setup-node@v1
              with:
                  node-version: '20'

            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: eu-central-1

            - name: npm install
              run: npm install --legacy-peer-deps

            - name: clean
              run: gatsby clean

            - name: build
              run: npm run build

            - name: Upload file to S3
              env:
                  S3_CONTENTS_BUCKET: ${{ secrets.S3_CONTENTS_BUCKET }}
              run: |
                  aws s3 sync ./public s3://$S3_CONTENTS_BUCKET/ --quiet
